# Generated by Django 3.1.5 on 2021-01-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='Пользователь')),
                ('workplace', models.IntegerField(verbose_name='Номер рабочего места')),
                ('datetime_from', models.CharField(max_length=20, verbose_name='Со скольки хотите начать работать')),
                ('datetime_to', models.CharField(max_length=20, verbose_name='До скольки хотите работать')),
            ],
            options={
                'verbose_name': 'Бронь рабочего места',
                'verbose_name_plural': 'Бронь рабочих мест',
            },
        ),
    ]
